"""Statement and declaration transformers."""
import textwrap
from pathlib import Path

from aura.transpiler.ast import *
from aura.transpiler.transformers.expressions import (
    ExpressionTransformer,
    catch_type_name,
    mangle_member,
    py_safe_name,
)


def _collect_declared_names(statements):
    """Collect names bound by a function body (locals, loop vars, patterns).

    Used to decide whether a bare identifier shadows a module-level member.
    Nested function bodies are included: their locals are separate scopes in
    Python, but over-approximating here only means a module member is *not*
    rewritten inside a nested function that happens to rebind the name, which
    is the safe direction.
    """
    names = set()
    stack = list(statements or [])
    while stack:
        node = stack.pop()
        if node is None:
            continue
        if isinstance(node, (list, tuple)):
            stack.extend(node)
            continue
        if isinstance(node, (VarDecl, ConstDecl)):
            target = node.name
            if isinstance(target, str):
                names |= set(StatementTransformer._declared_names(target))
        elif isinstance(node, FunctionDecl):
            names.add(node.name)
            for param in getattr(node, 'params', []) or []:
                if getattr(param, 'name', None):
                    names.add(param.name)
        elif isinstance(node, Parameter):
            if getattr(node, 'name', None):
                names.add(node.name)
        # Descend into every child node so nested blocks and functions are
        # covered. Only Aura AST nodes are traversed (never arbitrary objects).
        if not isinstance(node, Node):
            continue
        for value in vars(node).values():
            if isinstance(value, (list, tuple)):
                stack.extend(value)
            elif isinstance(value, Node):
                stack.append(value)
    return names


class StatementTransformer:
    def __init__(self):
        self.expr_transformer = ExpressionTransformer()
        self.indent_level = 0
        # Path of the file being transformed, when known. Used to resolve a
        # module's sibling re-exports relative to the source folder.
        self.source_path = None
        # Module-level imports hoisted from a facade module's re-exports; the
        # program transformer emits them before the body.
        self._module_reexport_imports = []
        self.class_members = {} # class_name -> {member_name: (visibility, owner)}
        self.in_class_scope = False
        # Counter for temporary variables generated by destructuring.
        self._destructure_counter = 0
        # Stack of local-name sets, one per enclosing function body. Used to
        # decide when a hoisted closure needs a `nonlocal` declaration.
        self.function_scopes = []
        # Set True when a generated __init__ needs the module-level sentinel.
        self.uses_aura_unset = False
        # Set True when traits/generics need the abc/typing prelude.
        self.uses_oop_prelude = False
        # Prelude needs recorded during transformation (enum/labeled loops).
        self.has_enum = False
        self.has_label = False
        # Names bound at module scope; assigning to one inside a function needs
        # a `global` declaration in the generated Python.
        self.module_bindings = set()
        # Stack (one per function) of module names assigned inside the body.
        self._global_assignments = []
        # Top-level module names brought in by `import`/`from ... import`.
        # Used to tell a library-managed base class (`pydantic.BaseModel`,
        # `attrs`, `enum.Enum`) apart from an Aura class, so the Aura
        # constructor machinery does not fight the library's metaclass.
        self.imported_modules = set()

    def transform(self, node):
        if node is None:
            return ""

        method_name = f"transform_{node.__class__.__name__}"
        method = getattr(self, method_name, None)
        if method:
            return method(node)

        raise NotImplementedError(f"No transformer for {node.__class__.__name__}")

    def _indent(self):
        return "    " * self.indent_level

    def _record_global_assignment(self, name):
        """Note that ``name`` (a module binding) is assigned inside a function.

        Python treats an assigned name as local to the function unless it is
        declared ``global``, so generated code must add that declaration.
        """
        if (self._global_assignments and isinstance(name, str)
                and name in self.module_bindings):
            self._global_assignments[-1].add(name)

    def _global_decl_line(self):
        if not self._global_assignments or not self._global_assignments[-1]:
            return ""
        names = ", ".join(sorted(self._global_assignments[-1]))
        return f"{self._indent()}    global {names}\n"

    def _nonlocal_decl_line(self, node, enclosing):
        """Return a `nonlocal` line for a nested function's captured locals.

        A nested ``def`` that assigns to a name bound in an enclosing function
        makes that name local to itself in Python, so the assignment must be
        declared ``nonlocal`` to mutate the captured binding. Names that the
        function declares itself (params, local ``let``/``const``, nested
        defs) or that live at module scope are excluded.
        """
        from aura.transpiler.transformers.expressions import (
            _collect_closure_names,
        )
        assigned: set = set()
        declared = {p.name for p in (node.params or [])}
        _collect_closure_names(node.body, assigned, declared)
        captured = (assigned - declared) & enclosing
        if not captured:
            return ""
        names = ", ".join(sorted(captured))
        return f"{self._indent()}    nonlocal {names}\n"

    @staticmethod
    def _safe_binding(name):
        """Map a declaration target to Python-safe spellings.

        Handles plain names and tuple/list destructuring targets like
        ``(a, b)`` by rewriting each component. Pattern characters (``*``,
        parentheses, brackets) are preserved.
        """
        if not isinstance(name, str):
            return name
        stripped = name.strip()
        if stripped[:1] in '([' and stripped[-1:] in ')]':
            inner = name[name.index(stripped[:1]) + 1:len(name) - 1]
            parts = []
            for part in inner.split(','):
                token = part.strip()
                if token.startswith('*'):
                    parts.append('*' + py_safe_name(token[1:].strip()))
                elif token:
                    parts.append(py_safe_name(token))
                else:
                    parts.append('')
            open_b, close_b = stripped[0], stripped[-1]
            return f"{open_b}{', '.join(parts)}{close_b}"
        return py_safe_name(name)

    @staticmethod
    def _declared_names(name):
        """Return the individual names bound by a declaration target string."""
        if not name:
            return []
        if isinstance(name, str) and name[:1] in '([' and name[-1:] in ')]':
            names = []
            for part in name[1:-1].replace('*', ' ').split(','):
                token = part.strip().strip('()[]{}')
                if token and token.isidentifier():
                    names.append(token)
            return names
        return [name] if isinstance(name, str) and name.isidentifier() else []

    def _decorator_line(self, dec):
        """Render a single decorator, including arguments and keyword args."""
        self.expr_transformer.used_decorators.append(dec.name)
        parts = []
        for a in dec.args:
            if isinstance(a, SpreadExpr):
                # `*xs` / `**kw` must not be wrapped: `@d((*xs))` is invalid.
                expr = self.expr_transformer.transform(a.expr)
                parts.append(f"{'**' if a.is_dict else '*'}{expr}")
            else:
                parts.append(self.expr_transformer.transform(a))
        for key, value in dec.kwargs.items():
            parts.append(f"{key}={self.expr_transformer.transform(value)}")
        if parts:
            return f"@{dec.name}({', '.join(parts)})\n"
        return f"@{dec.name}\n"

    def _block(self, statements):
        """Transform a list of statements into indented block.

        Hoisted helpers (block lambdas, block expressions) are emitted as
        nested functions at the start of the *current* block. Keeping them in
        the enclosing lexical scope lets them capture `self` and local
        variables, which module-level hoisting would break.
        """
        self.indent_level += 1
        indent = "    " * self.indent_level
        lines = []
        pending = self.expr_transformer.hoisted_functions
        for stmt in statements:
            before = len(pending)
            code = self.transform(stmt)
            new_hoists = pending[before:]
            if new_hoists:
                del pending[before:]
                for helper in new_hoists:
                    for line in helper.split('\n'):
                        lines.append(indent + line)
            if code:
                for line in code.split('\n'):
                    if line.strip():
                        lines.append(indent + line)
        self.indent_level -= 1
        if not lines:
            # Python requires a non-empty suite after every `:`. An Aura block
            # may legitimately be empty (`if x { }`), so emit `pass` with the
            # body's indentation instead of producing invalid Python.
            return indent + "pass"
        return '\n'.join(lines)

    # ========== Declarations ==========
    def transform_VarDecl(self, node):
        name = node.name
        # Track declared locals for closure `nonlocal` analysis.
        if self.function_scopes:
            for local_name in self._declared_names(node.name):
                self.function_scopes[-1].add(local_name)
        # Visibility only mangles names inside a class body, where Python's
        # name mangling is meaningful and member access is mangled to match.
        # For module-level and local variables the modifier is compile-time
        # metadata only; mangling the declaration alone would break every
        # later reference to it.
        if self.in_class_scope:
            info = self.expr_transformer.member_visibilities.get(name)
            vis, owner = (info if info else ('public', None))
            if node.visibility is not None:
                vis = node.visibility
            name = mangle_member(owner, name, vis)

        # Dict/struct destructuring: `let {name, age} = obj`. Python has no
        # matching binding form, so each field becomes an explicit lookup.
        if isinstance(name, str) and name.lstrip().startswith('{'):
            return self._emit_dict_destructure(name, node.value)

        name = self._safe_binding(name)

        if node.value:
            value = self.expr_transformer.transform(node.value)
            return f"{name} = {value}"
        else:
            return f"{name} = None"

    _DICT_PATTERN_RE = None

    def _emit_dict_destructure(self, pattern, value_node):
        """Compile `{a, b} = source` into one binding per source field."""
        if value_node is None:
            raise SyntaxError("dict destructuring requires a value on the right")
        source = self.expr_transformer.transform(value_node)
        fields = self._dict_pattern_fields(pattern)
        if not fields:
            raise SyntaxError(f"empty dict destructuring pattern: {pattern!r}")
        name_mangled = self.in_class_scope
        lines = []
        # Evaluate the source once so side effects are not repeated.
        self._destructure_counter += 1
        temp = f"_aura_destructure_{self._destructure_counter}"
        lines.append(f"{temp} = {source}")
        for field, alias in fields:
            target = alias
            if name_mangled:
                info = self.expr_transformer.member_visibilities.get(target)
                if info is not None:
                    vis, owner = info
                    target = mangle_member(owner, target, vis)
            lines.append(f"{py_safe_name(target)} = {temp}[{field!r}]")
        return "\n".join(lines)

    @staticmethod
    def _dict_pattern_fields(pattern):
        """Parse `{a, b: c}` into (source_key, target_name) pairs."""
        inner = pattern.strip()
        if inner.startswith('{') and inner.endswith('}'):
            inner = inner[1:-1]
        fields = []
        for part in inner.split(','):
            part = part.strip()
            if not part:
                continue
            if ':' in part:
                source_key, target = part.split(':', 1)
                source_key = source_key.strip().strip('\'"')
                target = target.strip()
            else:
                source_key = part.strip('\'"')
                target = part.strip()
            if not target.isidentifier():
                raise SyntaxError(
                    f"invalid dict destructuring target: {target!r}"
                )
            fields.append((source_key, target))
        return fields

    def transform_ConstDecl(self, node):
        value = self.expr_transformer.transform(node.value)
        return f"{self._safe_binding(node.name)} = {value}  # const"

    def transform_FunctionDecl(self, node):
        decorators_code = ""
        # Handle static/volatile
        if node.is_static:
            decorators_code += "@staticmethod\n"
        if node.is_volatile:
             decorators_code += "# volatile\n"

        for dec in node.decorators:
            decorators_code += self._decorator_line(dec)

        name = node.name
        if self.in_class_scope:
            if node.visibility == 'private': name = f"__{name}"
            elif node.visibility == 'protected': name = f"_{name}"

        params = []
        for param in node.params:
            if param.name == '*' and not param.is_variadic:
                # Bare `*` separator — marks subsequent params as keyword-only.
                params.append('*')
            elif param.is_kwonly:
                params.append(f"**{py_safe_name(param.name)}")
            elif param.is_variadic:
                params.append(f"*{py_safe_name(param.name)}")
            elif param.default:
                default = self.expr_transformer.transform(param.default)
                params.append(f"{py_safe_name(param.name)}={default}")
            else:
                params.append(py_safe_name(param.name))

        params_str = ", ".join(params)

        async_kw = "async " if node.is_async else ""

        if node.body is None:
            return f"{decorators_code}{async_kw}def {node.name}({params_str}): pass"
        elif isinstance(node.body, list):
            enclosing = set()
            for scope in self.function_scopes:
                enclosing |= scope
            self.function_scopes.append(set())
            self._global_assignments.append(set())
            # Locally-bound names shadow module-level members, so bare
            # references to them must stay bare.
            local_names = {p.name for p in node.params if getattr(p, 'name', None)}
            local_names |= _collect_declared_names(node.body)
            self.expr_transformer._local_scopes.append(local_names)
            try:
                body_code = self._block(node.body)
                global_decl = self._global_decl_line()
            finally:
                self.expr_transformer._local_scopes.pop()
                self.function_scopes.pop()
                self._global_assignments.pop()
            nonlocal_decl = ""
            if enclosing and body_code.strip():
                nonlocal_decl = self._nonlocal_decl_line(
                    node, enclosing)
            if not body_code.strip():
                body_code = self._indent() + "    pass"
            else:
                prefix = ""
                if global_decl:
                    prefix += global_decl
                if nonlocal_decl:
                    prefix += nonlocal_decl
                if prefix:
                    body_code = prefix + body_code
            return f"{decorators_code}{async_kw}def {node.name}({params_str}):\n{body_code}"
        else:
            # Expression body
            expr_code = self.expr_transformer.transform(node.body)
            return f"{decorators_code}{async_kw}def {node.name}({params_str}): return {expr_code}"

    def transform_ClassDecl(self, node):
        decorators_code = ""
        for dec in node.decorators:
            decorators_code += self._decorator_line(dec)

        base = ""
        bases = []
        if node.base_class:
            if isinstance(node.base_class, str):
                self._register_base_names(node.base_class)
                bases.append(node.base_class)
            else:
                bases.append(self.expr_transformer.transform(node.base_class))
        if getattr(node, 'is_abstract', False):
            # An abstract class cannot be instantiated. Making it an ABC gives
            # the same guarantee at runtime that the rule checker enforces at
            # compile time, and pairs with the `@abstractmethod` markers on its
            # `abstract def` members.
            bases.append('_aura_abc.ABC')
            self.uses_oop_prelude = True
        if getattr(node, 'type_params', None):
            bases.append(self._generic_bases(node.type_params))
            self.uses_oop_prelude = True
        if bases:
            base = f"({', '.join(bases)})"

        self.indent_level += 1
        old_in_class = self.in_class_scope
        self.in_class_scope = True

        # A base class managed by a Python library (a dotted base such as
        # `enum.Enum`, `pydantic.BaseModel` or `django.db.models.Model`) owns
        # its own construction protocol — often through a metaclass that
        # consumes class-body attributes before `__init__` ever runs. The
        # Aura-generated constructor and accessors must not be injected on top
        # of such a base; the fields stay as ordinary class attributes.
        external_base = self._has_external_base(
            node.base_class, has_header_fields=bool(node.header_fields))
        emit_accessors = True
        if external_base:
            # The fields are plain class attributes; drop any generated
            # get_/set_ accessors that would shadow the base's own API.
            emit_accessors = False

        # Header fields (`class User(private name: str, age: int = 0)`) are
        # turned into ordinary VarDecl members so they flow through exactly the
        # same constructor/accessor machinery as body-declared fields. They are
        # placed first, and the header order is preserved.
        header_fields = self._header_field_decls(node)

        # Populate visibility map for expressions
        current_vis = {}
        # Inherit from every base class. `node.base_class` is a comma-joined
        # string, so it must be split: keying on the whole string only matched
        # a single bare base and silently dropped inherited visibility for
        # multiple inheritance and dotted bases.
        for base_name in self._base_names(node.base_class):
            if base_name in self.class_members:
                current_vis.update(self.class_members[base_name])

        # Add current members. Each entry is (visibility, owner) where owner is
        # the class that declares the member, so inherited private members keep
        # their defining class's mangling prefix even when referenced here.
        for member in list(header_fields) + list(node.body):
            if hasattr(member, 'name') and hasattr(member, 'visibility'):
                current_vis[member.name] = (member.visibility, node.name)
            if isinstance(member, Method):
                self.expr_transformer.known_method_names.add(member.name)

        # Save to global map
        self.class_members[node.name] = current_vis

        old_vis = self.expr_transformer.member_visibilities
        self.expr_transformer.member_visibilities = current_vis

        # Automatic __init__ and __match_args__ for instance fields
        # Note: static fields go directly into class body, not __init__
        member_body = list(header_fields) + list(node.body)
        instance_fields = [m for m in member_body
                           if isinstance(m, VarDecl) and not m.is_static]
        methods = [m for m in node.body if isinstance(m, Method)]
        has_manual_init = any(m.name == '__init__' for m in methods)
        init_code = ""
        if instance_fields and not has_manual_init and not external_base:
            # A module-level sentinel lets an explicit `None` override a field
            # default, instead of being indistinguishable from "argument not
            # supplied" (which the old `x if x is not None else default` could
            # not do).
            #
            # The constructor's parameters live in a namespace that already
            # contains `self`, so a field whose Aura name is `self` cannot use
            # its raw spelling as a parameter. Only `self` is a hard collision:
            # the catch-all below is renamed when a field takes its spelling,
            # which keeps `C(kwargs=...)` binding the field rather than being
            # swallowed by the catch-all.
            param_names = self._constructor_param_names(instance_fields)
            catch_all = 'kwargs'
            while catch_all in param_names.values():
                catch_all += '_'
            params = ", ".join(
                f"{param_names[f.name]}=_aura_unset" for f in instance_fields)
            if params: params += ", "
            params += f"**{catch_all}"

            assign_lines = []
            for f in instance_fields:
                name = mangle_member(node.name, f.name, f.visibility)
                pname = param_names[f.name]

                if f.value:
                    if self._is_descriptor_value(f.value):
                        # A field initialised to a descriptor (`__get__`/
                        # `__set__`) must live on the class so Python's
                        # descriptor protocol runs; a fresh descriptor per
                        # instance would shadow it. The class-level default is
                        # emitted below and the constructor only overrides it
                        # when the caller supplies a value.
                        assign_lines.append(
                            f"{self._indent()}    if {pname} is not _aura_unset:\n"
                            f"{self._indent()}        self.{name} = {pname}"
                        )
                        continue
                    default_py = self.expr_transformer.transform(f.value)
                    assign_lines.append(
                        f"{self._indent()}    self.{name} = {default_py} if {pname} is _aura_unset else {pname}"
                    )
                else:
                    assign_lines.append(
                        f"{self._indent()}    self.{name} = None if {pname} is _aura_unset else {pname}"
                    )
            assigns = "\n".join(assign_lines)

            # `__match_args__` must use the *runtime* attribute name (mangled
            # for private/protected fields); the raw Aura name would not exist.
            match_args = ", ".join(
                [f"'{mangle_member(node.name, f.name, f.visibility)}'"
                 for f in instance_fields])
            if len(instance_fields) == 1: match_args += ","
            super_line = ""
            if node.base_class:
                super_line = f"{self._indent()}    super().__init__(**{catch_all})\n"
            init_code = (
                f"{self._indent()}__match_args__ = ({match_args})\n"
                f"{self._indent()}def __init__(self, {params}):\n{super_line}{assigns}\n"
            )
            self.uses_aura_unset = True
        else:
            init_code = ""

        # Auto-generate get_<name>() for every field and set_<name>(value) for
        # every mutable field, unless the author already defined a method with
        # that name. Header fields default to immutable, so they get a getter
        # only unless declared `mut`. Public fields are included: a header or a
        # field is data, and accessors give it a stable API without exposing
        # the storage name.
        defined_methods = {m.name for m in methods}
        accessor_parts = []
        for f in instance_fields:
            if not emit_accessors:
                break
            mangled = mangle_member(node.name, f.name, f.visibility)
            getter = f"get_{f.name}"
            setter = f"set_{f.name}"
            if getter not in defined_methods:
                accessor_parts.append(
                    f"{self._indent()}def {getter}(self):\n"
                    f"{self._indent()}    return self.{mangled}\n"
                )
            if not f.mutable:
                continue
            if setter not in defined_methods:
                accessor_parts.append(
                    f"{self._indent()}def {setter}(self, value):\n"
                    f"{self._indent()}    self.{mangled} = value\n"
                )
        accessors_code = "".join(accessor_parts)

        # Only emit class-level defaults for fields that don't duplicate __init__ params.
        # Descriptor-valued fields (`x = NonData()`) are the exception: they
        # must be class attributes for the descriptor protocol to run, even
        # when the generated constructor owns the other fields.
        emit_field_defaults = has_manual_init or not instance_fields or external_base
        descriptor_fields = {
            f.name for f in instance_fields if self._is_descriptor_value(f.value)
        }

        body_parts = []
        class_indent = self._indent()
        # Header fields are emitted first. When the generated constructor owns
        # them they exist only as parameters; when a manual `new` overrides the
        # constructor, they are also emitted as class-level defaults so the
        # generated accessors resolve even if the author forgets to assign one.
        if emit_field_defaults:
            for f in header_fields:
                name = mangle_member(node.name, f.name, f.visibility)
                default_py = (self.expr_transformer.transform(f.value)
                              if f.value is not None else "None")
                body_parts.append(self._indent() + f"{name} = {default_py}")
        for member in node.body:
            if isinstance(member, VarDecl):
                # Static fields always live on the class. Instance fields are
                # emitted at class level only when an auto-generated __init__
                # is not handling them, or when the field is a descriptor that
                # must stay on the class for its protocol to run.
                if (not member.is_static and not emit_field_defaults
                        and member.name not in descriptor_fields):
                    continue
                body_parts.append(self._indent() + self.transform(member))
            elif isinstance(member, ConstDecl):
                # A class-level `const` lives on the class, never on instances,
                # and is never a constructor parameter. It still honours
                # visibility so `private const` is mangled like any member.
                const_name = mangle_member(
                    node.name, member.name, member.visibility or 'public')
                const_value = self.expr_transformer.transform(member.value)
                line = f"{const_name} = {const_value}  # const"
                if member.is_volatile:
                    line = "# volatile\n" + line
                body_parts.append(self._indent() + line)
            elif isinstance(member, Method):
                self.indent_level -= 1
                method_code = self.transform(member)
                self.indent_level += 1
                body_parts.append(
                    class_indent + method_code.replace('\n', '\n' + class_indent))
            else:
                body_parts.append(self._indent() + self.transform(member))
        body_code = "\n".join(body_parts)
        if body_code:
            body_code += "\n"

        # Reset and finish
        final_body = init_code + accessors_code + body_code
        if not final_body.strip():
            # Keep the class body indented even when it is empty (an empty
            # class still needs a `pass` under the class header).
            final_body = self._indent() + "pass"
        self.indent_level -= 1
        self.in_class_scope = old_in_class
        self.expr_transformer.member_visibilities = old_vis

        return f"{decorators_code}class {node.name}{base}:\n{final_body}"

    def _is_descriptor_value(self, value):
        """Return True when a field's default is a descriptor instance.

        A descriptor is a field default that is itself a call or member path
        whose defining class declares ``__get__``, ``__set__`` or
        ``__delete__``. Aura class members are tracked by name in
        ``class_members``; a native Python factory (``@property``-like helper)
        is reported as a descriptor too, because keeping its result on the
        class is exactly what makes the protocol work.
        """
        if value is None:
            return False
        # A call to a locally-declared class, e.g. `x = NonData()`.
        target = None
        if isinstance(value, CallExpr):
            target = value.func
        elif isinstance(value, Identifier):
            target = value
        if target is None:
            return False
        if isinstance(target, Identifier):
            owner = target.name
        elif isinstance(target, MemberExpr):
            owner = target.member
        else:
            return False
        members = self.class_members.get(owner)
        if not members:
            return False
        return any(name in members for name in (
            '__get__', '__set__', '__delete__'))

    def transform_Method(self, node):
        decorators_code = ""
        if getattr(node, 'is_abstract', False):
            # `abstract def` is a signature only. Marking it with
            # `@abstractmethod` makes Python refuse to instantiate any concrete
            # subclass that forgets to implement it, mirroring the compile-time
            # E309 check.
            decorators_code += "@_aura_abc.abstractmethod\n"
            self.uses_oop_prelude = True
        if node.is_property:
            decorators_code += "@property\n"
        if node.is_static:
            decorators_code += "@staticmethod\n"
        if node.is_classmethod:
            decorators_code += "@classmethod\n"
        if node.is_volatile:
            decorators_code += "# volatile\n"
        for dec in node.decorators:
            if dec.name in ('property', 'staticmethod', 'classmethod'):
                continue
            decorators_code += self._decorator_line(dec)

        name = node.name
        # Python protocol methods (dunders) must never be name-mangled; doing so
        # would turn `__str__` into `____str__` and break the protocol.
        if not (name.startswith('__') and name.endswith('__')):
            info = self.expr_transformer.member_visibilities.get(name)
            vis, owner = (info if info else ('public', None))
            if node.visibility is not None:
                vis = node.visibility
            name = mangle_member(owner, name, vis)

        if node.is_static:
            params = []
        elif node.is_classmethod:
            params = ["cls"]
        elif node.name == '__init__':
            params = ["self"]
        else:
            params = ["self"]
        for param in node.params:
            if param.name in ("self", "cls"):
                continue
            if param.name == '*' and not param.is_variadic:
                # Bare `*` separator — marks subsequent params as keyword-only.
                params.append('*')
            elif param.is_kwonly:
                params.append(f"**{py_safe_name(param.name)}")
            elif param.is_variadic:
                params.append(f"*{py_safe_name(param.name)}")
            elif param.default:
                default = self.expr_transformer.transform(param.default)
                params.append(f"{py_safe_name(param.name)}={default}")
            else:
                params.append(py_safe_name(param.name))

        params_str = ", ".join(params)
        async_kw = "async " if getattr(node, 'is_async', False) else ""

        if node.body is None:
            return f"{decorators_code}{async_kw}def {name}({params_str}): pass"
        elif isinstance(node.body, list):
            # A method body is a function scope: a `guard ... else { return }`
            # returns from the method (not a module-level SystemExit).
            self.function_scopes.append(set())
            self._global_assignments.append(set())
            try:
                body_code = self._block(node.body)
                global_decl = self._global_decl_line()
            finally:
                self.function_scopes.pop()
                self._global_assignments.pop()
            if not body_code.strip():
                # A nested function body needs one extra indentation level
                # relative to the `def` line.
                body_code = self._indent() + "    pass"
            elif global_decl:
                body_code = global_decl + body_code
            return f"{decorators_code}{async_kw}def {name}({params_str}):\n{body_code}"
        else:
            expr_code = self.expr_transformer.transform(node.body)
            return (f"{decorators_code}{async_kw}def {name}({params_str}): "
                    f"return {expr_code}")

    def transform_TypeDecl(self, node):
        # Aura types are erased at compile time; emit a best-effort Python
        # runtime alias so the name still exists (e.g. `UserId = int`) and
        # document the original Aura spelling in a comment.
        py_type = self._aura_type_to_python(node.type_expr)
        return f"{node.name} = {py_type}  # type alias: {node.type_expr}"

    _SIMPLE_TYPES = {
        'int': 'int',
        'float': 'float',
        'str': 'str',
        'bool': 'bool',
        'bytes': 'bytes',
        'none': 'None',
        'null': 'None',
        'any': 'object',
        'Never': 'type(None)',
    }

    def _aura_type_to_python(self, type_text):
        """Best-effort conversion of an Aura type expression to Python."""
        if type_text is None:
            return 'object'
        # Type annotations may be AST nodes (SimpleType, GenericType, ...)
        # when constructed programmatically; fall back to their name if so.
        if not isinstance(type_text, str):
            name = getattr(type_text, 'name', None)
            if name:
                type_text = name
            else:
                return 'object'
        text = type_text.strip()
        if text in self._SIMPLE_TYPES:
            return self._SIMPLE_TYPES[text]
        if text.startswith('[') and text.endswith(']'):
            return 'list'
        if text.startswith('{') and text.endswith('}'):
            inner = text[1:-1]
            if ':' in inner:
                return 'dict'
            return 'set'
        if '->' in text or text.startswith('('):
            return 'object'
        if '|' in text:
            # Translate each union component: `int | none` → `int | None`.
            parts = [self._aura_type_to_python(p.strip()) for p in text.split('|')]
            return ' | '.join(parts)
        if text.isidentifier():
            return text
        return 'object'

    def transform_TraitDecl(self, node):
        # Traits are interfaces. Python has no native traits, so a trait
        # becomes an abstract base class. Methods with a body keep their
        # default implementation; signature-only methods become
        # @abstractmethod, so a subclass that fails to implement one cannot be
        # instantiated (instead of failing only when the method is called).
        bases = []
        if node.base_class:
            bases.append(node.base_class)
        bases.append('_aura_abc.ABC')
        if node.type_params:
            bases.append(self._generic_bases(node.type_params))
        header = f"class {node.name}({', '.join(bases)}):"
        self.indent_level += 1
        class_indent = self._indent()
        # Give trait members their owner so method bodies and fields resolve
        # visibility/mangling with the trait as the declaring class.
        trait_vis = {}
        for member in node.members:
            if hasattr(member, 'name') and hasattr(member, 'visibility'):
                trait_vis[member.name] = (member.visibility, node.name)
        old_tvis = self.expr_transformer.member_visibilities
        self.expr_transformer.member_visibilities = trait_vis
        body_lines = []
        for member in node.members:
            if isinstance(member, Method):
                if member.body:
                    self.indent_level -= 1
                    impl = self.transform(member)
                    self.indent_level += 1
                    body_lines.append(
                        class_indent + impl.replace('\n', '\n' + class_indent))
                else:
                    signature = self._trait_method_signature(member)
                    body_lines.append(class_indent + "@_aura_abc.abstractmethod")
                    async_kw = "async " if getattr(member, 'is_async', False) else ""
                    body_lines.append(class_indent + f"{async_kw}def {signature}:")
                    body_lines.append(class_indent + "    raise NotImplementedError")
            elif isinstance(member, VarDecl):
                default = 'None'
                if member.value is not None:
                    default = self.expr_transformer.transform(member.value)
                name = mangle_member(node.name, member.name, member.visibility)
                body_lines.append(class_indent + f"{name} = {default}")
            elif isinstance(member, ConstDecl):
                # Trait-level constant: lives on the trait, never on instances.
                value = self.expr_transformer.transform(member.value)
                name = mangle_member(node.name, member.name, member.visibility)
                body_lines.append(class_indent + f"{name} = {value}  # const")
        self.indent_level -= 1
        self.expr_transformer.member_visibilities = old_tvis
        if not body_lines:
            body_lines.append(class_indent + "pass")
        self.uses_oop_prelude = True
        return header + "\n" + "\n".join(body_lines)

    @staticmethod
    def _generic_bases(type_params):
        """Render ``[T, U]`` as ``_aura_Generic[_T, _U]`` with TypeVars."""
        vars_ = [f"_aura_TypeVar('{p}')" for p in type_params]
        return f"_aura_Generic[{', '.join(vars_)}]"

    def _register_base_names(self, base_class):
        """Record each base class name as a referenced identifier.

        Base names are emitted verbatim, so they never flow through
        ``transform_Identifier``. Registering them lets prelude detection see
        e.g. `class MyError extends Error` and inject the `Error` alias.
        """
        for part in str(base_class).split(','):
            name = part.strip()
            if not name:
                continue
            # A dotted base (`pkg.Base`) only contributes its head, which is the
            # name that must resolve as a free identifier.
            head = name.split('.')[0].strip()
            if head:
                self.expr_transformer.seen_identifiers.add(head)

    @staticmethod
    def _base_names(base_class):
        """Split a comma-joined ``base_class`` string into a list of names."""
        if not base_class:
            return []
        return [part.strip() for part in str(base_class).split(',') if part.strip()]

    def _constructor_param_names(self, instance_fields):
        """Return a collision-free Python parameter name per instance field.

        The generated `__init__` always binds `self` (and `cls` is reserved by
        convention), so a field whose Aura name is one of those cannot use its
        raw spelling as a parameter: `def __init__(self, self=...)` is invalid
        Python. Names are made unique within the constructor by appending
        underscores, and the choice is a pure function of the field list, so
        the parameter and its uses stay consistent. The catch-all `**kwargs`
        parameter is renamed by the caller when a field claims that spelling.
        """
        reserved = {'self', 'cls', '_aura_unset'}
        used = set()
        names = {}
        for field in instance_fields:
            base = py_safe_name(field.name)
            candidate = base
            while candidate in reserved or candidate in used:
                candidate += '_'
            used.add(candidate)
            names[field.name] = candidate
        return names

    def _has_external_base(self, base_class, has_header_fields=False):
        """Return True when a base is a Python library class, not an Aura class.

        A dotted base (`enum.Enum`, `django.db.models.Model`) or a name bound by
        a local `import`/`from ... import` is owned by Python; Aura must not
        generate a constructor or accessors that fight the library's metaclass.
        A bare name that resolves to an Aura class is left to the normal path.

        Exception: when the class declares its own header fields
        (`class App extends flask.Flask(debug_mode: bool = false)`), the author
        is explicitly asking Aura to build a constructor for those fields, so
        the Aura machinery still runs.
        """
        if has_header_fields:
            return False
        for name in self._base_names(base_class):
            if '.' in name:
                return True
            if name in self.imported_modules:
                return True
        return False

    def _header_field_decls(self, node):
        """Turn `ClassDecl.header_fields` into ordinary instance-field VarDecls.

        Each header entry is ``(Parameter, visibility, mutable)``. The result is
        a VarDecl with the same name/type/default, so it flows through the
        shared constructor and accessor machinery unchanged. Header fields are
        never static and never const.
        """
        decls = []
        for entry in getattr(node, 'header_fields', None) or []:
            param, visibility, mutable = entry
            decl = VarDecl(
                param.name,
                mutable,
                param.type_annotation,
                param.default,
                visibility=visibility,
                is_static=False,
                is_volatile=False,
                owner=node.name,
            )
            location = getattr(param, 'location', None) or getattr(node, 'location', None)
            if location is not None:
                decl.with_location(location)
            decls.append(decl)
        return decls

    def _trait_method_signature(self, method):
        """Render a trait method's parameter list, preserving its signature."""
        if method.is_static:
            params = []
        elif method.is_classmethod:
            params = ["cls"]
        else:
            params = ["self"]
        for param in method.params or []:
            if param.name in ("self", "cls"):
                continue
            if param.name == '*' and not param.is_variadic:
                # Bare `*` separator — marks subsequent params as keyword-only.
                params.append('*')
            elif param.is_kwonly:
                params.append(f"**{py_safe_name(param.name)}")
            elif param.is_variadic:
                params.append(f"*{py_safe_name(param.name)}")
            elif param.default:
                default = self.expr_transformer.transform(param.default)
                params.append(f"{py_safe_name(param.name)}={default}")
            else:
                params.append(py_safe_name(param.name))
        return f"{method.name}({', '.join(params)})"

    def transform_EnumDecl(self, node):
        """Emit a Python enum. Auto-numbered members continue from the last
        explicit integer value (so `enum E { A, B = 3, C }` gives C == 4)."""
        self.has_enum = True
        header = f"class {node.name}(_aura_enum.Enum):"
        body_lines = []
        next_auto = 1
        for member_name, value in node.members:
            if value is not None:
                rendered = self.expr_transformer.transform(value)
                body_lines.append(self._indent() + f"    {member_name} = {rendered}")
                if isinstance(value, IntLiteral):
                    next_auto = int(value.value) + 1
                else:
                    next_auto += 1
            else:
                body_lines.append(self._indent() + f"    {member_name} = {next_auto}")
                next_auto += 1
        return header + "\n" + "\n".join(body_lines)

    # ========== Statements ==========
    def transform_AssertStmt(self, node):
        cond = self.expr_transformer.transform(node.condition)
        if node.message:
            msg = self.expr_transformer.transform(node.message)
            return f"assert {cond}, {msg}"
        return f"assert {cond}"

    def transform_ExprStmt(self, node):
        if isinstance(node.expr, BlockExpr):
            return "\n".join([self.transform(s) for s in node.expr.statements])

        # A compile-time macro expanded in statement position may produce a
        # sequence of statements (`swap(a, b)` expands to bindings plus two
        # assignments). Expand it here so those statements are emitted directly
        # instead of being wrapped in a helper function that returns a value.
        macro_statements = self._macro_statement(node.expr)
        if macro_statements is not None:
            return "\n".join(self.transform(s) for s in macro_statements)

        # Check if it's an assignment (BinaryOp with '=')
        # Aura parsers assignments as BinaryOp expressions.
        # In Python, assignment is a statement.
        if isinstance(node.expr, BinaryOp) and node.expr.op == '=':
            left = self.expr_transformer.transform(node.expr.left)
            # Remove outer parens from left if present (though usually identifier)
            if left.startswith('(') and left.endswith(')'):
                left = left[1:-1]
            self._record_assign_targets(node.expr.left)

            right = self.expr_transformer.transform(node.expr.right)
            return f"{left} = {right}"
        elif isinstance(node.expr, BinaryOp) and node.expr.op in ('+=', '-=', '*=', '/=', '%=', '**=', '&=', '|=', '^=', '<<=', '>>='):
            # Computed assignments are also statements in Python
            left = self.expr_transformer.transform(node.expr.left)
            if left.startswith('(') and left.endswith(')'):
                left = left[1:-1]
            self._record_assign_targets(node.expr.left)
            right = self.expr_transformer.transform(node.expr.right)
            op = node.expr.op
            return f"{left} {op} {right}"
        elif isinstance(node.expr, BinaryOp) and node.expr.op == '??=':
            # Null-coalescing assignment: `x ??= v` -> `x = x if x is not None else v`
            # For complex LHS, evaluate once via a temp variable to avoid triple-evaluation.
            left = self.expr_transformer.transform(node.expr.left)
            if left.startswith('(') and left.endswith(')'):
                left = left[1:-1]
            self._record_assign_targets(node.expr.left)
            right = self.expr_transformer.transform(node.expr.right)
            if left.isidentifier():
                return f"{left} = {left} if {left} is not None else {right}"
            _tmp = f"_aura_nc_{id(node) & 0xFFFF:04x}"
            return f"{_tmp} = {left}; {left} = {_tmp} if {_tmp} is not None else {right}"

        expr = node.expr

        # Safety: unwrap nested ExprStmt if parser wrapped redundantly
        # Use Duck Typing / Name check to avoid class identity issues
        attempts = 0
        while expr.__class__.__name__ == 'ExprStmt':
            expr = expr.expr
            attempts += 1
            if attempts > 100:
                raise Exception("Infinite recursion unwrapping ExprStmt")

        return self.expr_transformer.transform(expr)

    def _macro_statement(self, expr):
        """Return a macro expansion's statement list, or None.

        A macro whose expansion is a ``BlockExpr`` used as a bare statement is
        emitted as its constituent statements, so an expansion can affect the
        surrounding scope (bindings, assignments) rather than only compute a
        value inside a hoisted function.
        """
        expr_transformer = self.expr_transformer
        registry = getattr(expr_transformer, 'macro_registry', None)
        if registry is None or not len(registry):
            return None
        if not isinstance(expr, CallExpr) or not isinstance(expr.func, Identifier):
            return None
        if expr.func.name not in registry:
            return None
        if expr.func.name in getattr(expr_transformer, 'user_declared_names', set()):
            return None
        if expr_transformer._is_shadowed(expr.func.name):
            return None
        replacement = expr_transformer._maybe_expand_macro(expr, render=False)
        if isinstance(replacement, BlockExpr):
            return replacement.statements
        return None

    def _record_assign_targets(self, target):
        """Record module-level names assigned by ``target`` (Identifier/tuple)."""
        from aura.transpiler.ast import Identifier, ListLiteral, TupleLiteral
        if target is None:
            return
        if isinstance(target, Identifier):
            self._record_global_assignment(target.name)
        elif isinstance(target, (TupleLiteral, ListLiteral)):
            for el in target.elements:
                self._record_assign_targets(el)

    def transform_IfStmt(self, node):
        cond = self.expr_transformer.transform(node.condition)
        then_body = self._block(node.then_body)

        result = f"if {cond}:\n{then_body}"

        if node.else_body:
            else_body = self._block(node.else_body)
            result += f"\nelse:\n{else_body}"

        return result

    def transform_UnlessStmt(self, node):
        # unless → if not
        cond = self.expr_transformer.transform(node.condition)
        body = self._block(node.body)

        result = f"if not ({cond}):\n{body}"

        if node.else_body:
            else_body = self._block(node.else_body)
            result += f"\nelse:\n{else_body}"

        return result

    def transform_GuardStmt(self, node):
        # guard condition else { ... } → if not condition: ...
        #
        # A bare top-level `guard cond else { return }` is Aura's idiom for
        # "bail out of the program". Python forbids a bare `return` at module
        # level, so those guard bodies are rewritten to `raise SystemExit`
        # instead of emitting invalid Python.
        cond = self.expr_transformer.transform(node.condition)
        else_body = self._render_guard_else(node.else_body)
        return f"if not ({cond}):\n{else_body}"

    def _render_guard_else(self, else_body):
        if not getattr(self, 'function_scopes', None):
            # Module scope: rewrite a leading bare `return` into SystemExit.
            rewritten = [
                self._module_return_to_exit(stmt) for stmt in (else_body or [])
            ]
            if any(r is not None for r in rewritten):
                else_body = [r if r is not None else stmt
                             for r, stmt in zip(rewritten, else_body or [], strict=False)]
        return self._block(else_body)

    @staticmethod
    def _module_return_to_exit(stmt):
        """Return a rewritten statement for a module-level guard body.

        ``return`` (bare or with a value) becomes ``raise SystemExit(...)`` so
        it is valid Python and terminates the program with the intended code.
        Returns ``None`` when the statement needs no rewriting.
        """
        if isinstance(stmt, ReturnStmt):
            if stmt.value is None:
                return ThrowStmt(CallExpr(Identifier('SystemExit'), [], {}))
            return ThrowStmt(CallExpr(Identifier('SystemExit'), [stmt.value], {}))
        return None

    def transform_WhileStmt(self, node):
        cond = self.expr_transformer.transform(node.condition)
        if node.label:
            return self._labeled_loop(node, f"while {cond}:")
        body = self._block(node.body)
        return f"while {cond}:\n{body}"

    def transform_UntilStmt(self, node):
        # until condition → while not condition
        cond = self.expr_transformer.transform(node.condition)
        if node.label:
            return self._labeled_loop(node, f"while not ({cond}):")
        body = self._block(node.body)
        return f"while not ({cond}):\n{body}"

    def transform_ForStmt(self, node):
        pattern = self.expr_transformer.transform(node.pattern)

        if node.step is not None:
            iterable = self._iterable_with_step(node.iterable, node.step)
        else:
            iterable = self.expr_transformer.transform(node.iterable)
        if node.label:
            return self._labeled_loop(node, f"for {pattern} in {iterable}:")
        body = self._block(node.body)
        return f"for {pattern} in {iterable}:\n{body}"

    def _iterable_with_step(self, iterable, step_node):
        """Render a `for ... step N` iterable correctly.

        Handles the three shapes Aura allows:
        * ``range(...)`` call  -> fold the step into the call
        * ``a..b`` range expr  -> attach step to the range
        * any other iterable   -> fall back to a Python slice ``items[::step]``
        """
        from aura.transpiler.ast import CallExpr, RangeExpr
        from aura.transpiler.ast import Identifier as _Ident

        if isinstance(iterable, CallExpr) and isinstance(iterable.func, _Ident) \
                and iterable.func.name == 'range':
            step = self.expr_transformer.transform(step_node)
            args = [self.expr_transformer.transform(a) for a in iterable.args]
            if len(args) >= 3:
                args[2] = step
            else:
                args.append(step)
            return f"range({', '.join(args)})"

        if isinstance(iterable, RangeExpr):
            # Create a copy to avoid mutating the original AST node.
            from aura.transpiler.ast import RangeExpr as _RE
            _copy = _RE(iterable.start, iterable.end, step_node)
            return self.expr_transformer.transform(_copy)

        step = self.expr_transformer.transform(step_node)
        base = self.expr_transformer.transform(iterable)
        return f"{base}[::{step}]"

    def _labeled_loop(self, node, header):
        """Emit a loop supporting labeled `break`/`continue`.

        `break label` raises `_AuraBreak`, caught around the whole loop.
        `continue label` raises `_AuraContinue`, caught around the loop body.
        """
        label = node.label
        self.has_label = True
        # Body wrapped so `continue label` is handled in place.
        self.indent_level += 1
        inner_indent = self._indent()
        self.indent_level += 1
        body_indent = self._indent()

        body_lines = []
        pending = self.expr_transformer.hoisted_functions
        for stmt in node.body:
            before = len(pending)
            code = self.transform(stmt)
            # A block lambda or block expression hoists a helper function; it
            # must be emitted inside the loop body (before the statement that
            # calls it) or the generated name is undefined. This mirrors
            # `_block`, and dropping them was a `NameError` at runtime.
            new_hoists = pending[before:]
            if new_hoists:
                del pending[before:]
                for helper in new_hoists:
                    for line in helper.split('\n'):
                        if line.strip():
                            body_lines.append(body_indent + line)
            if code:
                for line in code.split('\n'):
                    if line.strip():
                        body_lines.append(body_indent + line)
        self.indent_level -= 2

        inner = (
            f"{inner_indent}try:\n"
            + ("\n".join(body_lines) if body_lines else f"{body_indent}pass") + "\n"
            f"{inner_indent}except _AuraContinue as _aura_c:\n"
            f"{body_indent}if _aura_c.label != {label!r}:\n"
            f"{body_indent}    raise\n"
            f"{body_indent}continue"
        )
        loop = f"{header}\n{inner}"
        return (
            "try:\n"
            + textwrap.indent(loop, "    ") + "\n"
            f"except _AuraBreak as _aura_b:\n"
            f"    if _aura_b.label != {label!r}:\n"
            f"        raise"
        )

    def transform_LoopStmt(self, node):
        if node.label:
            return self._labeled_loop(node, "while True:")
        body = self._block(node.body)
        return f"while True:\n{body}"

    def transform_BreakStmt(self, node):
        if node.label:
            return f"raise _AuraBreak({node.label!r})"
        return "break"

    def transform_ContinueStmt(self, node):
        if node.label:
            return f"raise _AuraContinue({node.label!r})"
        return "continue"

    def transform_ReturnStmt(self, node):
        if node.value:
            value = self.expr_transformer.transform(node.value)
            return f"return {value}"
        return "return"

    def transform_ThrowStmt(self, node):
        if node.value:
            # `throw "message"` must raise an exception object: Python does not
            # allow raising bare strings. Wrap non-exception values so the
            # documented `throw ValueError(...)` form and the convenient string
            # form both work.
            if isinstance(node.value, StrLiteral):
                return f"raise Exception({self.expr_transformer.transform(node.value)})"
            value = self.expr_transformer.transform(node.value)
            return f"raise {value}"
        return "raise"

    def transform_TryStmt(self, node):
        try_body = self._block(node.try_body)
        result = f"try:\n{try_body}"

        for catch in node.catch_clauses:
            exc_type = catch_type_name(catch.exception_type)
            var_name = f" as {catch.var_name}" if catch.var_name else ""
            catch_body = self._block(catch.body)
            result += f"\nexcept {exc_type}{var_name}:\n{catch_body}"

        if node.finally_body is not None:
            finally_body = self._block(node.finally_body)
            result += f"\nfinally:\n{finally_body}"

        return result

    def transform_WithStmt(self, node):
        items = []
        for expr, var_name in node.items:
            expr_code = self.expr_transformer.transform(expr)
            if var_name:
                items.append(f"{expr_code} as {var_name}")
            else:
                items.append(expr_code)

        items_str = ", ".join(items)
        body = self._block(node.body)
        async_kw = "async " if getattr(node, 'is_async', False) else ""
        return f"{async_kw}with {items_str}:\n{body}"

    def transform_ImportStmt(self, node):
        # import a, b as c -> import a, b as c
        # import a.b {x, y} -> from a.b import x, y
        # import a.b as c -> import a.b as c
        # import py.re -> import re ; import py.os.path -> import os.path as path
        if getattr(node, 'is_python', False):
            return self._transform_python_import(node)
        self._record_import_names(
            [mod for mod, _alias in getattr(node, 'modules', None) or []],
            [module for module, _alias in getattr(node, 'modules', None) or []])
        if getattr(node, 'modules', None):
            parts = []
            for mod, mod_alias in node.modules:
                parts.append(f"{mod} as {mod_alias}" if mod_alias else mod)
            return "import " + ", ".join(parts)
        if node.items:
            parts = []
            for item in node.items:
                name, item_alias = item if isinstance(item, tuple) else (item, None)
                if item_alias:
                    parts.append(f"{name} as {item_alias}")
                else:
                    parts.append(name)
            if node.alias:
                # `import a.b as c {x}` is ambiguous; import the module under
                # the alias *and* bind the selected names.
                lines = [f"import {node.module} as {node.alias}"]
                lines.append(f"from {node.module} import {', '.join(parts)}")
                return "\n".join(lines)
            return f"from {node.module} import {', '.join(parts)}"
        if node.alias:
            self._record_import_names([node.alias], [node.module])
            return f"import {node.module} as {node.alias}"
        self._record_import_names([node.module], [node.module])
        return f"import {node.module}"

    def _transform_python_import(self, node):
        """Emit a host-Python import written with the `py.` prefix.

        `import py.re` binds the last path segment (`re`), matching the Aura
        rule that `py.re` brings in `re`; `import py.os.path` therefore binds
        `path` (unlike Python's `import os.path`, which binds `os`). An explicit
        `as` alias always wins.
        """
        parts = []
        for mod, mod_alias in getattr(node, 'modules', None) or []:
            bound = mod_alias or mod.split('.')[-1]
            parts.append(f"{mod} as {bound}")
            self.imported_modules.add(bound)
        if parts:
            return "import " + ", ".join(parts)
        bound = node.alias or node.module.split('.')[-1]
        self.imported_modules.add(bound)
        return f"import {node.module} as {bound}"

    def transform_FromImport(self, node):
        items = []
        bindings = []
        for name, alias in node.items:
            if name == '*':
                items.append('*')
            elif alias:
                items.append(f"{name} as {alias}")
                bindings.append(alias)
            else:
                items.append(name)
                bindings.append(name)
        # `from enum import Enum` binds a library class name; `from App import X`
        # binds an Aura sibling, which must not be treated as external.
        # A `py.` import is always external, whatever the module looks like.
        if getattr(node, 'is_python', False) or not self._is_local_module(node.module):
            self.imported_modules.update(bindings)
        return f"from {node.module} import {', '.join(items)}"

    def _record_import_names(self, bound_names, module_names):
        """Mark bound import names that resolve to a non-Aura module.

        Used by class inheritance to tell a library base (`enum.Enum`) from an
        Aura sibling import, so the Aura constructor machinery only steps aside
        for library-managed bases.
        """
        for bound, module in zip(bound_names, module_names, strict=False):
            if not self._is_local_module(module):
                self.imported_modules.add(bound)
                self.imported_modules.add(bound.split('.')[0])

    def _is_local_module(self, module_name):
        """Return True when ``module_name`` names an Aura module in this project.

        Aura's own modules are compiled alongside the program, so they are not
        "external"; a Python library (``enum``, ``django.db``) is.
        """
        if not module_name:
            return False
        root = module_name.split('.')[0]
        if root in getattr(self, 'aura_module_names', set()):
            return True
        source = getattr(self, 'source_path', None)
        if source is None:
            return False
        base = Path(source).parent / root
        return base.with_suffix('.aura').is_file() or base.is_dir()

    def transform_MatchStmt(self, node):
        expr = self.expr_transformer.transform(node.expr)

        # Python 3.10+ match statement
        result = f"match {expr}:\n"

        # Increase indent for cases
        self.indent_level += 1

        for case in node.cases:
            pattern = self.expr_transformer.transform(case.pattern)
            if case.guard:
                guard = self.expr_transformer.transform(case.guard)
                result += f"{self._indent()}case {pattern} if {guard}:\n"
            else:
                result += f"{self._indent()}case {pattern}:\n"

            # Block handles its own indent increment usually?
            # If _block adds ANOTHER indent... check _block logic.
            # Assuming _block increments, renders, decrements.
            # So calling _block here works for case body relative to case.
            body = self._block(case.body)
            result += body + "\n"

        self.indent_level -= 1
        return result

    def transform_Module(self, node):
        """Transform a module declaration into a namespaced class.

        Module members are static so `Module.member` keeps working. A dotted
        module name (`module Outer.Inner`) becomes nested classes so the
        attribute path `Outer.Inner.member` resolves in Python.
        """
        parts = node.name.split('.')
        # A facade whose file is named after its own folder
        # (`App/App.aura`) backs the package itself, so its members are bound
        # directly at module level. Wrapping them in a class would nest them
        # under `App.App` instead of the package the import names.
        if self._is_package_facade(node.name):
            reexport_imports, bindings = self._module_reexport_lines(
                node.name, node.members, getattr(node, 'exports', None),
                getattr(node, 'reexports', None) or [])
            self._module_reexport_imports.extend(reexport_imports)
            # Bindings are built for a class body; at module level they are
            # already at the right indent once dedented.
            lines = [line.lstrip() if line.strip() else line
                     for line in bindings]
            for member in node.members:
                if isinstance(member, FunctionDecl):
                    member.is_static = True
                code = self.transform(member)
                if code and code.strip():
                    lines.append(code)
            return "\n".join(lines) if lines else "pass"

        # Innermost class holds the members; wrap it in one class per prefix.
        inner = self._module_class(parts[-1], node.members,
                                   getattr(node, 'exports', None),
                                   getattr(node, 'reexports', None))
        for part in reversed(parts[:-1]):
            inner = textwrap.indent(inner, "    ")
            inner = f"class {part}:\n{inner}"
        return inner

    def _is_package_facade(self, module_name):
        """True when this module backs the package that contains its file.

        `App/App.aura` is the entry point Python imports as `App`, so a module
        named `App` in a folder named `App` must not add another namespace
        level. A module in a plainly-named file stays a namespaced class.
        """
        if not self.source_path:
            return False
        source = Path(self.source_path).resolve()
        return (source.stem == source.parent.name == module_name)

    def _module_class(self, name, members, exports=None, reexports=None):
        header = f"class {name}:"
        body_lines = []
        exports = set(exports or ())
        # `export Name` (no declaration) re-exports a name from a sibling
        # source file; `export Name from "mod"` names the source explicitly.
        # Resolve against the folder holding the facade, then bind the name.
        # The sibling imports are hoisted to module level (a dotted import
        # inside a class body would bind the top-level package name as a class
        # attribute, shadowing the module itself).
        reexport_imports, reexport_lines = self._module_reexport_lines(
            name, members, exports, reexports or [])
        self._module_reexport_imports.extend(reexport_imports)
        # Module-level data members (const/let/static) live on the class; a bare
        # reference to one inside a module function must resolve to
        # `Module.name`. Register them for the duration of the body transform.
        module_data = {}
        for member in members:
            if isinstance(member, (VarDecl, ConstDecl)):
                module_data[member.name] = name
        self.expr_transformer._module_scopes.append(module_data)
        # Members are private to the file unless exported. A private member is
        # stored under a mangled name so an external `Module.member` access
        # fails at runtime (the rule checker reports E308 first).
        private_names = {}
        for member in members:
            member_name = getattr(member, 'name', None)
            if member_name and member_name not in exports:
                private_names[member_name] = mangle_member(name, member_name, 'private')
        old_module_privates = self.expr_transformer._module_privates
        self.expr_transformer._module_privates = {name: private_names}
        try:
            for member in members:
                if isinstance(member, FunctionDecl):
                    member.is_static = True
                code = self.transform(member)
                # `class`/`def` declarations emit their own header; data
                # members need the mangled assignment applied to the target.
                if code and code.strip():
                    for line in code.split("\n"):
                        body_lines.append("    " + line if line.strip() else line)
        finally:
            self.expr_transformer._module_privates = old_module_privates
            self.expr_transformer._module_scopes.pop()
        if not body_lines:
            body_lines.append("    pass")
        if reexport_lines:
            body_lines = reexport_lines + body_lines
        # Rename private declarations to their mangled runtime names.
        text = header + "\n" + "\n".join(body_lines)
        for public_name, mangled in private_names.items():
            text = self._rename_module_member(text, public_name, mangled)
        return text

    def _module_reexport_lines(self, module_name, members, exports, reexports):
        """Resolve a module's bare `export Name` entries to bindings.

        Returns ``(imports, bindings)``: module-level import lines (hoisted out
        of the class body) and the in-class assignment lines that bind each
        requested name. A name the module declares itself needs no binding.
        """
        if not reexports:
            return [], []
        from aura.transpiler.modules import resolve_reexport

        declared = {getattr(m, 'name', None) for m in members}
        base_dir = None
        if self.source_path:
            base_dir = Path(self.source_path).resolve().parent

        imports = []
        bindings = []
        imported = {}
        for item in reexports:
            for requested in item.names:
                # The module's own declaration wins: `export X` where X is
                # declared here is just a public marker, already handled.
                if requested in declared:
                    continue
                if base_dir is None:
                    raise SyntaxError(
                        f"module '{module_name}': cannot resolve re-export "
                        f"'{requested}' without a source file path")
                found = resolve_reexport(requested, base_dir, item.source)
                if found is None:
                    where = f' from "{item.source}"' if item.source else ''
                    raise SyntaxError(
                        f"module '{module_name}': nowhere to resolve "
                        f"'{requested}'{where}; expected a sibling "
                        f"'{requested.lower()}.aura' or a same-named "
                        f"declaration in this file")
                _path, module_path, declares_name = found
                # A facade that lives in its own package directory
                # (`App/App.aura`) must import its siblings through that
                # package (`App.components`), not as top-level modules.
                qualified = self._qualify_module_path(module_path)
                local = imported.get(qualified)
                if local is None:
                    local = "_aura_reexport_" + str(len(imported))
                    imported[qualified] = local
                    imports.append(f"import {qualified} as {local}")
                if declares_name:
                    # `export Components` -> bind the declared name.
                    bindings.append(f"    {requested} = {local}.{requested}")
                else:
                    # `export Utils` -> the whole sibling module is the
                    # namespace, so `App.Utils.double(...)` works.
                    bindings.append(f"    {requested} = {local}")
        return imports, bindings

    def _qualify_module_path(self, module_path):
        """Prefix a sibling module path with the facade's package name.

        `App/App.aura` re-exporting `components` must import `App.components`
        so the sibling resolves inside the package rather than as a top-level
        module. The prefix is the name of the directory holding the facade,
        which is also the package Python will register it under.
        """
        if not self.source_path:
            return module_path
        source = Path(self.source_path).resolve()
        directory = source.parent
        # `App/App.aura` is the entry point of the `App` package, so its
        # siblings are imported as `App.<sibling>`. A facade in a plain file
        # (`facade.aura`) re-exports top-level modules instead.
        if directory.name != source.stem:
            return module_path
        return f"{directory.name}.{module_path}"

    # Indentation (in spaces) of a member declared directly in a module body.
    # Module members are emitted one level inside the module class.
    _MODULE_MEMBER_INDENT = 4

    @staticmethod
    def _rename_module_member(text, public_name, mangled):
        """Rename a private module member's declaration to its mangled name.

        Handles the declaration shapes the transformer emits: `def name(...)`,
        `class name(...)`, `class name:`, and a data assignment `name = ...` or
        an annotated `name: T = ...`. Only a member declared at the module
        body's own indent level is renamed, so a nested local of the same name
        keeps its binding. Calls to the member inside the module are rewritten
        separately by the expression transformer, which knows the mapping.
        """
        safe = py_safe_name(public_name)
        if safe == mangled:
            return text
        out = []
        for line in text.split("\n"):
            stripped = line.lstrip()
            indent = line[:len(line) - len(stripped)]
            # Only a member declared directly in the module body (one indent
            # level) is renamed; a nested local of the same name is a different
            # binding and must keep its name.
            if len(indent) != StatementTransformer._MODULE_MEMBER_INDENT:
                out.append(line)
                continue
            for keyword, sep in (("def ", "("), ("class ", "("), ("class ", ":")):
                head = f"{keyword}{safe}"
                if stripped.startswith(head + sep) or stripped.startswith(head + " ("):
                    # Replace only the name, never a keyword prefix. Use the
                    # known keyword length: `prefix.index(safe)` would match a
                    # name that is a substring of the keyword (e.g. `f` in
                    # `def `), corrupting it to `de_M__f(`.
                    stripped = f"{keyword}{mangled}{stripped[len(head):]}"
                    break
            else:
                if (stripped.startswith(f"{safe} =")
                        or stripped.startswith(f"{safe}:")
                        or stripped.startswith(f"{safe} ")):
                    stripped = f"{mangled}{stripped[len(safe):]}"
            out.append(indent + stripped)
        return "\n".join(out)

    # ========== Helper: Transform patterns ==========
    def _transform_pattern(self, pattern):
        if isinstance(pattern, IdentifierPattern):
            return pattern.name
        elif isinstance(pattern, LiteralPattern):
            val = pattern.value
            # The parser may wrap a literal as an AST expression node.
            if isinstance(val, Expr):
                return self.expr_transformer.transform(val)
            if isinstance(val, str): return repr(val)
            if isinstance(val, bool): return str(val)
            if val is None: return "None"
            return str(val)
        elif isinstance(pattern, WildcardPattern):
            return "_"
        elif isinstance(pattern, ListPattern):
            pats = [self._transform_pattern(p) for p in pattern.patterns]
            if pattern.rest_pattern:
                pats.append(f"*{pattern.rest_pattern.name}")
            return f"[{', '.join(pats)}]"
        elif isinstance(pattern, DictPattern):
            fields = []
            for name, pat in pattern.field_patterns.items():
                 # Match Python dict pattern: {key: value}
                 # Python match dict syntax: {"key": value} or {k: v} if k is literal?
                 # Actually Python 3.10 match items are keys?
                 # case {"a": 1}:
                 fields.append(f'"{name}": {self._transform_pattern(pat)}')
            if pattern.rest_pattern:
                 fields.append(f"**{pattern.rest_pattern.name}")
            return f"{{{', '.join(fields)}}}"
        elif isinstance(pattern, ConstructorPattern):
            name = pattern.name
            args = [self._transform_pattern(p) for p in pattern.subpatterns]
            return f"{name}({', '.join(args)})"

        elif isinstance(pattern, OrPattern):
            pats = [self._transform_pattern(p) for p in pattern.patterns]
            return f"({' | '.join(pats)})"

        return "_"

